In [8]:
#import the needed package
import pandas as pd

In [9]:
#create the data frame
data = {
    "id": [101, 102, 103, 104, 105, 106],
    "age": [24, 31, 27, 19, 42, 35],
    "group": ["A", "B", "A", "B", "A", "B"],
    "score": [81, 94, 88, 72, 91, 85]
}

df = pd.DataFrame(data)

#then show the df
df

,id,age,group,score
0,101,24,A,81
1,102,31,B,94
2,103,27,A,88
3,104,19,B,72
4,105,42,A,91
5,106,35,B,85


In [10]:
#show some information about it
df.head()
df.shape
df.columns
df.index
df.dtypes
df.info()
df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   id      6 non-null      int64 
 1   age     6 non-null      int64 
 2   group   6 non-null      object
 3   score   6 non-null      int64 
dtypes: int64(3), object(1)
memory usage: 324.0+ bytes


,id,age,score
count,6.000000,6.000000,6.000000
mean,103.500000,29.666667,85.166667
std,1.870829,8.189424,7.884584
min,101.000000,19.000000,72.000000
25%,102.250000,24.750000,82.000000
50%,103.500000,29.000000,86.500000
75%,104.750000,34.000000,90.250000
max,106.000000,42.000000,94.000000


How many observations are there?
There are 6 observations.

How many variables?
There are three variables.

Which columns are numeric?
The ID, age, and score columns are numeric.

What is the default index?
The default index is 4.

What does df.shape return?
It returns the number of observations followed by the number of columnms.


In [11]:
age = df["age"]
type(age)

pandas.core.series.Series

In [12]:
age_df = df[["age"]]
type(age_df)

pandas.core.frame.DataFrame

Two brackets indicates rows and columns, or part of a dataframe, while just the one set of brackets signifies a series, just a list of numbers versus both rows and columns.

In [13]:
df["score"]

0    81
1    94
2    88
3    72
4    91
5    85
Name: score, dtype: int64

In [14]:
df[["age", "score"]]

,age,score
0,24,81
1,31,94
2,27,88
3,19,72
4,42,91
5,35,85


In [16]:
analysis_df = df[["id", "group", "score"]]
analysis_df

,id,group,score
0,101,A,81
1,102,B,94
2,103,A,88
3,104,B,72
4,105,A,91
5,106,B,85


In [17]:
#select rows by position
df.iloc[0]

id       101
age       24
group      A
score     81
Name: 0, dtype: object

In [18]:
df.iloc[0:3]

,id,age,group,score
0,101,24,A,81
1,102,31,B,94
2,103,27,A,88


In [19]:
df.iloc[[0, 2, 5]]

,id,age,group,score
0,101,24,A,81
2,103,27,A,88
5,106,35,B,85


In [20]:
df.iloc[1:4, 1:3]

,age,group
1,31,B
2,27,A
3,19,B


What does the first argument to .iloc[] control?
The first argument controls the rows selected.

What does the second argument control?
The second argument controls the columns selected.

Is the stop value included in positional slicing?
No, the stop value is not included. It only counts to the number before it.

In [21]:
df = df.set_index("id")
df
df.index

Index([101, 102, 103, 104, 105, 106], dtype='int64', name='id')

In [22]:
df.loc[101]

age      24
group     A
score    81
Name: 101, dtype: object

In [23]:
df.iloc[0]

age      24
group     A
score    81
Name: 101, dtype: object

They identify the same observation here. Why do the two commands mean different things?
The command calling for row id 101 returns the row with that index, but the second command calling for row 0 finds the first row in the data, which happens to be index 101.

In [24]:
df.loc[101]

age      24
group     A
score    81
Name: 101, dtype: object

In [25]:
df.loc[[101, 103, 105]]

,age,group,score
id,,,
101,24,A,81
103,27,A,88
105,42,A,91


In [26]:
df.loc[
    [101, 103],
    ["age", "score"]
]

,age,score
id,,
101,24,81
103,27,88


In [27]:
df.loc[
    [102, 104, 106],
    ["age", "group", "score"]
]

,age,group,score
id,,,
102,31,B,94
104,19,B,72
106,35,B,85


In [28]:
small = pd.DataFrame(
    {"value": [10, 20, 30, 40]},
    index=[101, 205, 310, 412]
)

In [29]:
small.loc[205]

value    20
Name: 205, dtype: int64

In [30]:
small.iloc[1]

value    20
Name: 205, dtype: int64

.loc  uses row values
.iloc uses row indices

In [31]:
df.iloc[1:4]

,age,group,score
id,,,
102,31,B,94
103,27,A,88
104,19,B,72


In [32]:
df.loc[102:105]

,age,group,score
id,,,
102,31,B,94
103,27,A,88
104,19,B,72
105,42,A,91


Positional slicing works around usual indices, but label-based slicing identifies all mentioned values as necessary and also grabs the end of the interval.

In [33]:
df.loc[:, ["age", "score"]]

,age,score
id,,
101,24,81
102,31,94
103,27,88
104,19,72
105,42,91
106,35,85


In [34]:
df.loc[
    102:105,
    ["age", "score"]
]

,age,score
id,,
102,31,94
103,27,88
104,19,72
105,42,91


In [35]:
#challenge
df.loc[
    101:104,
    ["group", "score"]
]

,group,score
id,,
101,A,81
102,B,94
103,A,88
104,B,72


In [ ]:
condition = df["score"] > 80

condition
type(condition)

In [39]:
df.loc[condition]

,age,group,score
id,,,
101,24,A,81
102,31,B,94
103,27,A,88
105,42,A,91
106,35,B,85


The true or false values reflected in the condition series represent whether that given row heeds the condition or not.

In [40]:
df.loc[df["score"] > 80]

,age,group,score
id,,,
101,24,A,81
102,31,B,94
103,27,A,88
105,42,A,91
106,35,B,85


In [41]:
df.loc[df["age"] >= 30]

,age,group,score
id,,,
102,31,B,94
105,42,A,91
106,35,B,85


In [42]:
df.loc[df["group"] == "A"]

,age,group,score
id,,,
101,24,A,81
103,27,A,88
105,42,A,91


In [43]:
df.loc[
    (df["age"] < 30) &
    (df["score"] > 80)
]

,age,group,score
id,,,
101,24,A,81
103,27,A,88


In [44]:
df.loc[
    (df["group"] == "A") |
    (df["score"] > 90)
]

,age,group,score
id,,,
101,24,A,81
102,31,B,94
103,27,A,88
105,42,A,91


In [45]:
df.loc[
    ~(df["group"] == "A")
]

,age,group,score
id,,,
102,31,B,94
104,19,B,72
106,35,B,85


In [46]:
#challenge
df.loc[
    (df["age"] > 29) &
    (df["score"] > 84)
]

,age,group,score
id,,,
102,31,B,94
105,42,A,91
106,35,B,85


In [48]:
df.loc[
    (df["group"] == "A") &
    (df["score"] >= 90)
]

,age,group,score
id,,,
105,42,A,91


For this command, I predict that only observation 105 will abide by the condition.
And I was correct.

In [ ]:
df.loc[
    df["score"] >= 85,
    ["age", "group", "score"]
]

In [50]:
#challenge 
df.loc[
    df["age"] >= 30,
    ["group", "score"]
]

,group,score
id,,
102,B,94
105,A,91
106,B,85


In [55]:
#PART 15
df2 = pd.DataFrame(
    {
        "id": range(201, 209),
        "group": ["A", "B", "C", "A", "C", "B", "A", "C"],
        "score": [81, 94, 88, 72, 91, 85, 79, 96]
    }
).set_index("id")

df2

,group,score
id,,
201,A,81
202,B,94
203,C,88
204,A,72
205,C,91
206,B,85
207,A,79
208,C,96


In [52]:
df2.loc[
    df2["group"].isin(["A", "C"])
]

,group,score
id,,
201,A,81
203,C,88
204,A,72
205,C,91
207,A,79
208,C,96


In [56]:
#challenge 
df2.loc[
    (df2["group"].isin(["B","C"])) &
    (df2["score"] >= 85)
]

,group,score
id,,
202,B,94
203,C,88
205,C,91
206,B,85
208,C,96


In [57]:
# Missing Data
missing_df = pd.DataFrame(
    {
        "id": [1, 2, 3, 4, 5],
        "age": [21, 32, None, 45, 28],
        "score": [81, None, 77, 92, 88]
    }
).set_index("id")

In [61]:
missing_df
missing_df.isna()
missing_df.isna().sum()

age      1
score    1
dtype: int64

In [62]:
missing_df.loc[
    missing_df["score"].isna()
]

,age,score
id,,
2,32.0,NaN


In [63]:
missing_df.loc[
    missing_df["score"].notna()
]

,age,score
id,,
1,21.0,81.0
3,NaN,77.0
4,45.0,92.0
5,28.0,88.0


A zero score tells us an attribute about the subject, wether it be good or bad, but a missing score says the data is missing so we cannot make assumptions.

In [65]:
df["performance"] = "medium"

df.loc[
    df["score"] >= 90,
    "performance"
] = "high"

df.loc[
    df["score"] < 80,
    "performance"
] = "low"

In [66]:
df[df["score"] > 80]["score"] = 100

<positron-console-cell-66>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy


In [67]:
df.loc[
    df["score"] > 80,
    "score"
] = 100

The .loc command is cleaner since it's cleaner to read. The loc command more naturally selects on conditions, but subsetting a df on a condition is awkward when subsetting the traditional way. In addition, the command is very close to (and even warns) it could be a copy of the slice, as opposed to altering the original data. This means the actual dataframe might not change, but it definitely will with the .loc command.

In [68]:
analysis = df.loc[
    (df["age"] >= 18) &
    (df["group"] == "A") &
    (df["score"].notna())
]

In [69]:
#part 21
participants = pd.DataFrame(
    {
        "id": range(1001, 1011),
        "age": [22, 34, 29, 41, 19, 37, 26, 45, 31, 28],
        "group": ["A", "B", "A", "C", "B", "A", "C", "B", "A", "C"],
        "score": [78, 91, 85, 88, 72, 95, 81, 67, 90, 84]
    }
).set_index("id")

In [74]:
#A. Participants aged 30 or older
older = participants.loc[ participants["age"] >= 30 ]

In [75]:
#B. Participants in groups A or C
groups_ac = participants.loc[ participants["group"].isin(["A", "C"]) ]

In [ ]:
#C. Participants with scores at least 85
high_scores = participants.loc[ participants["score"] >= 85 ]

,age,group,score
id,,,
1002,34,B,91
1003,29,A,85
1004,41,C,88
1006,37,A,95
1009,31,A,90


In [ ]:
#D. Participants aged at least 30 AND scoring at least 85
older_high = participants.loc[ 
    (participants["age"] >= 30) &
    (participants["score"] >= 85)
 ]

,age,group,score
id,,,
1002,34,B,91
1004,41,C,88
1006,37,A,95
1009,31,A,90


In [78]:
#E. Only group and score for high scorers
older_high = participants.loc[
    (participants["score"] >= 85),
    ["group", "score"]
]

In [ ]:
#F. Group A participants scoring at least 80
group_a_good = participants.loc[
    (participants["score"] >= 80) &
    (participants["group"] == "A")
]

,age,group,score
id,,,
1003,29,A,85
1006,37,A,95
1009,31,A,90


In [82]:
#G. Participants who are NOT in group B
not_group_b = participants.loc[
    ~(participants["group"] == "B")
]

In [83]:
not_group_b.shape
not_group_b.head()
not_group_b.index

Index([1001, 1003, 1004, 1006, 1007, 1009, 1010], dtype='int64', name='id')

1. DataFrames
What does a pandas DataFrame provide that a list of dictionaries does not?
pandas can list column titles. Dictionaries can list keys, their data types, but it cannot store a name for a set of keys.

2. Series
What is the difference between:
df["age"]
and:
df[["age"]]?
The first creates a series and the second creates a dataframe.

3. .loc vs. .iloc
Explain the difference in one sentence.
.loc uses values to subset data, but iloc uses direct indicies for rows and columns to subset.

4. Boolean filtering
What does:
df["score"] >= 85
produce before it is used to subset a DataFrame?
Before it's subset, a boolean list of whether each row follows the condition is created.

5. Analysis populations
Why is a pandas filter more than simply a programming operation?
A pandas filter means you can filter on values, narrowing data down easier to subsets you want to use to analyze. It allows for the ease of data analysis.

6. Validation
Why should you inspect a filtered dataset even if no Python error occurred?
It's vital to ensure that the command works. For example, > or >= can be the difference between including or excluding a valid observation. It's necessary to at least spot check and ensure the code is doing what you want it to.

7. Reproducibility
How can explicit filtering criteria make statistical analyses easier to reproduce?
Using explicit criteria means any onlooker can understand what your code is doing. If someone approaches your code without being able to understand it, that could be problematic in a job scenario, especially were a supervisor might be overlooking your finished work.